export const TEAM_FLAGS: Record<string, string> = {
  // English Names
  "France": "🇫🇷",
  "Iraq": "🇮🇶",
  "Argentina": "🇦🇷",
  "Brazil": "🇧🇷",
  "Spain": "🇪🇸",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Germany": "🇩🇪",
  "Italy": "🇮🇹",
  "Portugal": "🇵🇹",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Croatia": "🇭🇷",
  "Uruguay": "🇺🇾",
  "Colombia": "🇨🇴",
  "Mexico": "🇲🇽",
  "USA": "🇺🇸",
  "United States": "🇺🇸",
  "Canada": "🇨🇦",
  "Morocco": "🇲🇦",
  "Senegal": "🇸🇳",
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "North Korea": "🇰🇵",
  "Australia": "🇦🇺",
  "Iran": "🇮🇷",
  "Saudi Arabia": "🇸🇦",
  "Ecuador": "🇪🇨",
  "Switzerland": "🇨🇭",
  "Poland": "🇵🇱",
  "Denmark": "🇩🇰",
  "Tunisia": "🇹🇳",
  "Cameroon": "🇨🇲",
  "Ghana": "🇬🇭",
  "Qatar": "🇶🇦",
  "Costa Rica": "🇨🇷",
  "Wales": "🏴󠁧󠁢qw󠁬󠁳󠁿", // note: standard Welsh flag character is 🏴󠁧󠁢󠁷󠁬󠁳󠁿, let's fix below
  "Wales_fix": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Ukraine": "🇺🇦",
  "Peru": "🇵🇪",
  "Chile": "🇨🇱",
  "Turkey": "🇹🇷",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Paraguay": "🇵🇾",
  "Venezuela": "🇻🇪",
  "Bolivia": "🇧🇴",
  "Panama": "🇵🇦",
  "Jamaica": "🇯🇲",
  "Honduras": "🇭🇳",
  "El Salvador": "🇸🇻",
  "Ivory Coast": "🇨🇮",
  "Nigeria": "🇳🇬",
  "Algeria": "🇩🇿",
  "Egypt": "🇪🇬",
  "South Africa": "🇿🇦",
  "Congo DR": "🇨🇩",
  "DR Congo": "🇨🇩",
  "New Zealand": "🇳🇿",
  "Curaçao": "🇨🇼",
  "Curacao": "🇨🇼",
  "Ireland": "🇮🇪",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Austria": "🇦🇹",
  "Czechia": "🇨🇿",
  "Serbia": "🇷🇸",
  "Hungary": "🇭🇺",
  "Greece": "🇬🇷",
  "Romania": "🇷🇴",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Georgia": "🇬🇪",
  "Albania": "🇦🇱",
  "Angola": "🇦🇴",
  "Cape Verde": "🇨🇻",
  "Guinea": "🇬🇳",
  "Uzbekistan": "🇺🇿",
  "Jordan": "🇯🇴",
  "Oman": "🇴🇲",
  "Bahrain": "🇧🇭",
  "Palestine": "🇵🇸",
  "China": "🇨🇳",
  "Syria": "🇸🇾",
  "Trinidad and Tobago": "🇹🇹",
  "Bosnia": "🇧🇦",
  "North Macedonia": "🇲🇰",
  "Mali": "🇲🇱",
  "Equatorial Guinea": "🇬🇶",
  "United Arab Emirates": "🇦🇪",
  "Iceland": "🇮🇸",
  "Finland": "🇫🇮",

  // Spanish Names
  "Francia": "🇫🇷",
  "Irak": "🇮🇶",
  "Brasil": "🇧🇷",
  "España": "🇪🇸",
  "Inglaterra": "🏴󠁧󠁢e󠁮󠁧󠁿",
  "Alemania": "🇩🇪",
  "Italia": "🇮🇹",
  "Países Bajos": "🇳🇱",
  "Holanda": "🇳🇱",
  "Bélgica": "🇧🇪",
  "Croacia": "🇭🇷",
  "México": "🇲🇽",
  "Estados Unidos": "🇺🇸",
  "Canadá": "🇨🇦",
  "Marruecos": "🇲🇦",
  "Japón": "🇯🇵",
  "Corea del Sur": "🇰🇷",
  "Corea del Norte": "🇰🇵",
  "Irán": "🇮🇷",
  "Arabia Saudita": "🇸🇦",
  "Suiza": "🇨🇭",
  "Polonia": "🇵🇱",
  "Dinamarca": "🇩🇰",
  "Túnez": "🇹🇳",
  "Camerún": "🇨🇲",
  "Gales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Ucrania": "🇺🇦",
  "Perú": "🇵🇪",
  "Turquía": "🇹🇷",
  "Suecia": "🇸🇪",
  "Noruega": "🇳🇴",
  "Panamá": "🇵🇦",
  "Costa de Marfil": "🇨🇮",
  "Argelia": "🇩🇿",
  "Egipto": "🇪🇬",
  "Sudáfrica": "🇿🇦",
  "Nueva Zelanda": "🇳🇿",
  "Irlanda": "🇮🇪",
  "Escocia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Hungría": "🇭🇺",
  "Grecia": "🇬🇷",
  "Rumanía": "🇷🇴",
  "Eslovaquia": "🇸🇰",
  "Eslovenia": "🇸🇮",
  "Cabo Verde": "🇨🇻",
  "Uzbekistán": "🇺🇿",
  "Jordania": "🇯🇴",
  "Omán": "🇴🇲",
  "Baréin": "🇧🇭",
  "Palestina": "🇵🇸",
  "Siria": "🇸🇾",
  "Trinidad y Tobago": "🇹🇹",
  "Macedonia del Norte": "🇲🇰",
  "Malí": "🇲🇱",
  "Guinea Ecuatorial": "🇬🇶",
  "Emiratos Árabes Unidos": "🇦🇪",
  "Islandia": "🇮🇸",
  "Finlandia": "🇫🇮",
};

// Fix Welsh and English flags in map
TEAM_FLAGS["Wales"] = "🏴󠁧󠁢󠁷󠁬󠁳󠁿";
TEAM_FLAGS["England"] = "🏴󠁧󠁢󠁥󠁮󠁧󠁿";
TEAM_FLAGS["Inglaterra"] = "🏴󠁧󠁢󠁥󠁮󠁧󠁿";

export function getTeamFlag(name: string): string {
  if (!name) return "";
  const cleanName = name.trim();
  return TEAM_FLAGS[cleanName] || "";
}
