"""
Edgebet — resolver de escudos por nombre normalizado de equipo.

Usamos los CDN públicos de ESPN: la URL incluye un team id estable.
Para equipos no mapeados devolvemos None y el frontend usa un fallback
(iniciales del equipo).
"""
from __future__ import annotations

# IDs de ESPN — visibles en site.api.espn.com/.../teams/{id}.
# https://a.espncdn.com/i/teamlogos/soccer/500/{id}.png
ESPN_TEAM_ID: dict[str, str] = {
    # ── Premier League ────────────────────────────────────────────────────
    "Man City":         "382",
    "Arsenal":          "359",
    "Liverpool":        "364",
    "Chelsea":          "363",
    "Aston Villa":      "362",
    "Tottenham":        "367",
    "Newcastle":        "361",
    "Man United":       "360",
    "West Ham":         "371",
    "Nott'm Forest":    "393",
    "Wolves":           "380",
    "Bournemouth":      "349",
    "Brighton":         "331",
    "Crystal Palace":   "384",
    "Leicester":        "375",
    "Ipswich":          "373",
    "Southampton":      "376",
    "Sunderland":       "366",
    "Burnley":          "379",
    "Everton":          "368",
    "Fulham":           "370",
    "Brentford":        "337",
    "Leeds United":     "357",
    "Leeds":            "357",
    # ── La Liga ──────────────────────────────────────────────────────────
    "Real Madrid":      "86",
    "Barcelona":        "83",
    "Atletico Madrid":  "1068",
    "Ath Bilbao":       "93",
    "Athletic Club":    "93",
    "Real Sociedad":    "89",
    "Villarreal":       "102",
    "Betis":            "244",
    "Real Betis":       "244",
    "Sevilla":          "243",
    "Valencia":         "94",
    "Girona":           "9812",
    "Celta":            "85",
    "Celta Vigo":       "85",
    "Getafe":           "2922",
    "Alaves":           "96",
    "Osasuna":          "97",
    "Mallorca":         "84",
    "Vallecano":        "101",
    "Rayo Vallecano":   "101",
    "Espanyol":         "88",
    "Oviedo":           "3447",
    "Elche":            "10205",
    "Levante":          "3727",
    # ── Bundesliga ───────────────────────────────────────────────────────
    "Bayern Munich":    "132",
    "Dortmund":         "124",
    "Borussia Dortmund": "124",
    "Leverkusen":       "125",
    "Bayer Leverkusen": "125",
    "RB Leipzig":       "11420",
    "Frankfurt":        "129",
    "Eintracht Frankfurt": "129",
    "Stuttgart":        "134",
    "VfB Stuttgart":    "134",
    "M'gladbach":       "268",
    "Borussia Monchengladbach": "268",
    "Mainz":            "131",
    "Werder Bremen":    "137",
    "Heidenheim":       "7846",
    "Augsburg":         "445",
    "Hoffenheim":       "7911",
    "Freiburg":         "127",
    "Wolfsburg":        "138",
    "St Pauli":         "133",
    "FC St. Pauli":     "133",
    "FC Koln":          "295",
    "Hamburg":          "128",
    "Union Berlin":     "598",
    # ── Serie A ──────────────────────────────────────────────────────────
    "Inter":            "110",
    "Inter Milan":      "110",
    "Milan":            "103",
    "AC Milan":         "103",
    "Juventus":         "111",
    "Napoli":           "114",
    "Roma":             "104",
    "AS Roma":          "104",
    "Lazio":            "105",
    "SS Lazio":         "105",
    "Atalanta":         "113",   # fixed (was 105 = Lazio)
    "Fiorentina":       "99",
    "Bologna":          "107",
    "Torino":           "100",
    "Udinese":          "106",
    "Genoa":            "1903",
    "Parma":            "115",
    "Cagliari":         "108",
    "Como":             "1579",
    "Verona":           "1898",
    "Hellas Verona":    "1898",
    "Empoli":           "1900",
    "Venezia":          "1902",
    "Lecce":            "1893",
    "Sassuolo":         "452",
    "Monza":            "16219",
    "Cremonese":        "13885",
    "Pisa":             "11244",
    "AC Pisa 1909":     "11244",
    # ── Ligue 1 ──────────────────────────────────────────────────────────
    "Paris SG":         "160",
    "PSG":              "160",
    "Monaco":           "174",
    "AS Monaco":        "174",
    "Marseille":        "176",
    "Olympique Marseille": "176",
    "Lyon":             "166",
    "Olympique Lyonnais": "166",
    "Lille":            "165",
    "Nice":             "171",
    "OGC Nice":         "171",
    "Rennes":           "159",
    "Stade Rennais":    "159",
    "Lens":             "164",
    "Racing Club de Lens": "164",
    "Nantes":           "168",
    "FC Nantes":        "168",
    "Brest":            "162",
    "Stade Brestois":   "162",
    "Strasbourg":       "163",
    "RC Strasbourg":    "163",
    "Lorient":          "169",
    "FC Lorient":       "169",
    "Le Havre":         "1263",
    "Toulouse":         "180",
    "Auxerre":          "161",
    "St Etienne":       "175",
    "Saint-Etienne":    "175",
    "Angers":           "12317",
    "Reims":            "172",
    "Stade Reims":      "172",
    "Montpellier":      "167",
    "Metz":             "170",
    "Paris FC":         "8497",
    # ── UEFA Champions League extras ─────────────────────────────────────
    "Barcelona":        "83",
}


def logo_url(team_name: str) -> str | None:
    """Devuelve URL del escudo o None si no está mapeado."""
    if not team_name:
        return None
    team_id = ESPN_TEAM_ID.get(team_name)
    if not team_id:
        return None
    return f"https://a.espncdn.com/i/teamlogos/soccer/500/{team_id}.png"
