"""
Edgebet — resolver de escudos por nombre normalizado de equipo.

Usamos los CDN públicos de ESPN: la URL incluye un team id estable.
Para equipos no mapeados devolvemos None y el frontend usa un fallback
(iniciales del equipo).
"""
from __future__ import annotations

# IDs de ESPN — visibles en site.api.espn.com/.../teams/{id}.
# https://a.espncdn.com/i/teamlogos/soccer/500/{id}.png
ESPN_TEAM_ID: dict[str, str] = {
    # ── Premier League ────────────────────────────────────────────────────
    "Man City":                     "382",
    "Manchester City":              "382",
    "Manchester City FC":           "382",
    "Arsenal":                      "359",
    "Arsenal FC":                   "359",
    "Liverpool":                    "364",
    "Liverpool FC":                 "364",
    "Chelsea":                      "363",
    "Chelsea FC":                   "363",
    "Aston Villa":                  "362",
    "Aston Villa FC":               "362",
    "Tottenham":                    "367",
    "Tottenham Hotspur":            "367",
    "Tottenham Hotspur FC":         "367",
    "Spurs":                        "367",
    "Newcastle":                    "361",
    "Newcastle United":             "361",
    "Newcastle United FC":          "361",
    "Man United":                   "360",
    "Manchester United":            "360",
    "Manchester United FC":         "360",
    "West Ham":                     "371",
    "West Ham United":              "371",
    "West Ham United FC":           "371",
    "Nott'm Forest":                "393",
    "Nottingham Forest":            "393",
    "Nottingham Forest FC":         "393",
    "Wolves":                       "380",
    "Wolverhampton":                "380",
    "Wolverhampton Wanderers":      "380",
    "Wolverhampton Wanderers FC":   "380",
    "Bournemouth":                  "349",
    "AFC Bournemouth":              "349",
    "Brighton":                     "331",
    "Brighton & Hove Albion":       "331",
    "Brighton & Hove Albion FC":    "331",
    "Crystal Palace":               "384",
    "Crystal Palace FC":            "384",
    "Leicester":                    "375",
    "Leicester City":               "375",
    "Leicester City FC":            "375",
    "Ipswich":                      "373",
    "Ipswich Town":                 "373",
    "Ipswich Town FC":              "373",
    "Southampton":                  "376",
    "Southampton FC":               "376",
    "Sunderland":                   "366",
    "Sunderland AFC":               "366",
    "Burnley":                      "379",
    "Burnley FC":                   "379",
    "Everton":                      "368",
    "Everton FC":                   "368",
    "Fulham":                       "370",
    "Fulham FC":                    "370",
    "Brentford":                    "337",
    "Brentford FC":                 "337",
    "Leeds United":                 "357",
    "Leeds":                        "357",
    "Leeds United AFC":             "357",
    # ── La Liga ──────────────────────────────────────────────────────────
    "Real Madrid":                      "86",
    "Real Madrid CF":                   "86",
    "Barcelona":                        "83",
    "FC Barcelona":                     "83",
    "Atletico Madrid":                  "1068",
    "Atlético Madrid":                  "1068",
    "Club Atlético de Madrid":          "1068",
    "Atletico de Madrid":               "1068",
    "Ath Bilbao":                       "93",
    "Athletic Club":                    "93",
    "Athletic Bilbao":                  "93",
    "Athletic de Bilbao":               "93",
    "Real Sociedad":                    "89",
    "Real Sociedad de Fútbol":          "89",
    "Villarreal":                       "102",
    "Villarreal CF":                    "102",
    "Betis":                            "244",
    "Real Betis":                       "244",
    "Real Betis Balompié":              "244",
    "Sevilla":                          "243",
    "Sevilla FC":                       "243",
    "Valencia":                         "94",
    "Valencia CF":                      "94",
    "Girona":                           "9812",
    "Girona FC":                        "9812",
    "Celta":                            "85",
    "Celta Vigo":                       "85",
    "RC Celta de Vigo":                 "85",
    "RC Celta":                         "85",
    "Getafe":                           "2922",
    "Getafe CF":                        "2922",
    "Alaves":                           "96",
    "Alavés":                           "96",
    "Deportivo Alavés":                 "96",
    "Deportivo Alaves":                 "96",
    "Osasuna":                          "97",
    "CA Osasuna":                       "97",
    "Mallorca":                         "84",
    "RCD Mallorca":                     "84",
    "Vallecano":                        "101",
    "Rayo Vallecano":                   "101",
    "Rayo Vallecano de Madrid":         "101",
    "Espanyol":                         "88",
    "RCD Espanyol":                     "88",
    "RCD Espanyol de Barcelona":        "88",
    "Oviedo":                           "3447",
    "Real Oviedo":                      "3447",
    "Elche":                            "10205",
    "Elche CF":                         "10205",
    "Levante":                          "3727",
    "Levante UD":                       "3727",
    # ── Bundesliga ───────────────────────────────────────────────────────
    "Bayern Munich":                "132",
    "FC Bayern München":            "132",
    "FC Bayern Munich":             "132",
    "Dortmund":                     "124",
    "Borussia Dortmund":            "124",
    "BVB":                          "124",
    "Leverkusen":                   "125",
    "Bayer Leverkusen":             "125",
    "Bayer 04 Leverkusen":          "125",
    "RB Leipzig":                   "11420",
    "Leipzig":                      "11420",
    "Frankfurt":                    "129",
    "Eintracht Frankfurt":          "129",
    "Stuttgart":                    "134",
    "VfB Stuttgart":                "134",
    "M'gladbach":                   "268",
    "Borussia Monchengladbach":     "268",
    "Borussia Mönchengladbach":     "268",
    "Gladbach":                     "268",
    "Mainz":                        "131",
    "1. FSV Mainz 05":              "131",
    "FSV Mainz 05":                 "131",
    "Werder Bremen":                "137",
    "SV Werder Bremen":             "137",
    "Heidenheim":                   "7846",
    "1. FC Heidenheim 1846":        "7846",
    "FC Heidenheim":                "7846",
    "Augsburg":                     "445",
    "FC Augsburg":                  "445",
    "Hoffenheim":                   "7911",
    "TSG 1899 Hoffenheim":          "7911",
    "TSG Hoffenheim":               "7911",
    "Freiburg":                     "127",
    "SC Freiburg":                  "127",
    "Wolfsburg":                    "138",
    "VfL Wolfsburg":                "138",
    "St Pauli":                     "133",
    "FC St. Pauli":                 "133",
    "FC St. Pauli 1910":            "133",
    "FC Koln":                      "295",
    "1. FC Köln":                   "295",
    "1. FC Koln":                   "295",
    "FC Köln":                      "295",
    "Hamburg":                      "128",
    "Hamburger SV":                 "128",
    "HSV":                          "128",
    "Union Berlin":                 "598",
    "1. FC Union Berlin":           "598",
    "FC Union Berlin":              "598",
    # ── Serie A ──────────────────────────────────────────────────────────
    "Inter":                        "110",
    "Inter Milan":                  "110",
    "FC Internazionale Milano":     "110",
    "Internazionale":               "110",
    "Milan":                        "103",
    "AC Milan":                     "103",
    "Juventus":                     "111",
    "Juventus FC":                  "111",
    "Napoli":                       "114",
    "SSC Napoli":                   "114",
    "Roma":                         "104",
    "AS Roma":                      "104",
    "Lazio":                        "105",
    "SS Lazio":                     "105",
    "Atalanta":                     "113",   # fixed (was 105 = Lazio)
    "Atalanta BC":                  "113",
    "Fiorentina":                   "99",
    "ACF Fiorentina":               "99",
    "Bologna":                      "107",
    "Bologna FC 1909":              "107",
    "Torino":                       "100",
    "Torino FC":                    "100",
    "Udinese":                      "106",
    "Udinese Calcio":               "106",
    "Genoa":                        "1903",
    "Genoa CFC":                    "1903",
    "Parma":                        "115",
    "Parma Calcio 1913":            "115",
    "Cagliari":                     "108",
    "Cagliari Calcio":              "108",
    "Como":                         "1579",
    "Como 1907":                    "1579",
    "Verona":                       "1898",
    "Hellas Verona":                "1898",
    "Hellas Verona FC":             "1898",
    "Empoli":                       "1900",
    "Empoli FC":                    "1900",
    "Venezia":                      "1902",
    "Venezia FC":                   "1902",
    "Lecce":                        "1893",
    "US Lecce":                     "1893",
    "Sassuolo":                     "452",
    "US Sassuolo Calcio":           "452",
    "Monza":                        "16219",
    "AC Monza":                     "16219",
    "Cremonese":                    "13885",
    "US Cremonese":                 "13885",
    "Pisa":                         "11244",
    "AC Pisa 1909":                 "11244",
    "Pisa Sporting Club":           "11244",
    # ── Ligue 1 ──────────────────────────────────────────────────────────
    "Paris SG":                     "160",
    "PSG":                          "160",
    "Paris Saint-Germain":          "160",
    "Paris Saint-Germain FC":       "160",
    "Monaco":                       "174",
    "AS Monaco":                    "174",
    "AS Monaco FC":                 "174",
    "Marseille":                    "176",
    "Olympique Marseille":          "176",
    "Olympique de Marseille":       "176",
    "OM":                           "176",
    "Lyon":                         "166",
    "Olympique Lyonnais":           "166",
    "OL":                           "166",
    "Lille":                        "165",
    "LOSC Lille":                   "165",
    "Lille OSC":                    "165",
    "Nice":                         "171",
    "OGC Nice":                     "171",
    "Rennes":                       "159",
    "Stade Rennais":                "159",
    "Stade Rennais FC 1901":        "159",
    "Stade Rennais FC":             "159",
    "Lens":                         "164",
    "Racing Club de Lens":          "164",
    "RC Lens":                      "164",
    "Nantes":                       "168",
    "FC Nantes":                    "168",
    "Brest":                        "162",
    "Stade Brestois":               "162",
    "Stade Brestois 29":            "162",
    "Strasbourg":                   "163",
    "RC Strasbourg":                "163",
    "RC Strasbourg Alsace":         "163",
    "Lorient":                      "169",
    "FC Lorient":                   "169",
    "Le Havre":                     "1263",
    "Le Havre AC":                  "1263",
    "HAC":                          "1263",
    "Toulouse":                     "180",
    "Toulouse FC":                  "180",
    "Auxerre":                      "161",
    "AJ Auxerre":                   "161",
    "St Etienne":                   "175",
    "Saint-Etienne":                "175",
    "AS Saint-Étienne":             "175",
    "AS Saint-Etienne":             "175",
    "Angers":                       "12317",
    "Angers SCO":                   "12317",
    "Reims":                        "172",
    "Stade Reims":                  "172",
    "Stade de Reims":               "172",
    "Montpellier":                  "167",
    "Montpellier HSC":              "167",
    "Metz":                         "170",
    "FC Metz":                      "170",
    "Paris FC":                     "8497",
    # ── UEFA Champions League extras ─────────────────────────────────────
    "Sporting CP":                  "467",
    "Sporting Lisboa":              "467",
    "Sporting Clube de Portugal":   "467",
    "Benfica":                      "212",
    "SL Benfica":                   "212",
    "Porto":                        "213",
    "FC Porto":                     "213",
    "Ajax":                         "139",
    "AFC Ajax":                     "139",
    "PSV":                          "148",
    "PSV Eindhoven":                "148",
    "Celtic":                       "186",
    "Celtic FC":                    "186",
    "Rangers":                      "188",
    "Rangers FC":                   "188",
    "Club Brugge":                  "12262",
    "Club Brugge KV":               "12262",
    "FC Brugge":                    "12262",
    "Red Bull Salzburg":            "17265",
    "FC Red Bull Salzburg":         "17265",
    "RB Salzburg":                  "17265",
    "Salzburg":                     "17265",
    "Shakhtar Donetsk":             "660",
    "FC Shakhtar Donetsk":          "660",
    "Shakhtar":                     "660",
    "Dinamo Zagreb":                "442",
    "GNK Dinamo Zagreb":            "442",
    "NK Dinamo Zagreb":             "442",
    "Young Boys":                   "3032",
    "BSC Young Boys":               "3032",
    "BSC YB":                       "3032",
    "Feyenoord":                    "143",
    "Feyenoord Rotterdam":          "143",
    "Galatasaray":                  "2656",
    "Galatasaray SK":               "2656",
    "Galatasaray AS":               "2656",
    "Fenerbahce":                   "500",
    "Fenerbahçe":                   "500",
    "Fenerbahce SK":                "500",
    "Besiktas":                     "502",
    "Beşiktaş":                     "502",
    "Besiktas JK":                  "502",

    # ── Liga MX ──────────────────────────────────────────────────────────
    "America":                      "227",
    "Club America":                 "227",
    "CF América":                   "227",
    "Club América":                 "227",
    "Cruz Azul":                    "228",
    "Guadalajara":                  "230",
    "Chivas":                       "230",
    "Deportivo Guadalajara":        "230",
    "Monterrey":                    "236",
    "CF Monterrey":                 "236",
    "Rayados":                      "236",
    "Pachuca":                      "237",
    "CF Pachuca":                   "237",
    "Tuzos":                        "237",
    "Leon":                         "234",
    "Club León":                    "234",
    "León":                         "234",
    "Tigres UANL":                  "243",
    "Tigres":                       "243",
    "UANL Tigres":                  "243",
    "Pumas UNAM":                   "242",
    "Pumas":                        "242",
    "UNAM":                         "242",
    "Necaxa":                       "224",
    "Club Necaxa":                  "224",
    "Santos Laguna":                "239",
    "Atlas":                        "225",
    "Atlas Guadalajara":            "225",
    "Atletico San Luis":            "10778",
    "Atlético San Luis":            "10778",
    "Toluca":                       "241",
    "Deportivo Toluca":             "241",
    "Tijuana":                      "9665",
    "Club Tijuana":                 "9665",
    "Xolos":                        "9665",
    "Mazatlan":                     "11960",
    "Mazatlán FC":                  "11960",
    "Puebla":                       "238",
    "Puebla FC":                    "238",
    "Juarez":                       "10800",
    "FC Juárez":                    "10800",
    "Bravos":                       "10800",
    "Queretaro":                    "229",
    "Querétaro":                    "229",
    "Gallos Blancos":               "229",
}


def logo_url(team_name: str) -> str | None:
    """Devuelve URL del escudo o None si no está mapeado."""
    if not team_name:
        return None
    team_id = ESPN_TEAM_ID.get(team_name)
    if not team_id:
        return None
    return f"https://a.espncdn.com/i/teamlogos/soccer/500/{team_id}.png"
